stages:
  - build
  - test

test-runner-image:
  stage: build
  image: docker:stable
  services:
    - name: docker:18.09.7-dind
      command: ["--insecure-registry=psy3.memcompute.com"]
  variables:
    CI_IMAGE: psy3.memcompute.com/memsql-spark-utils/test-runner
  script:
    - docker info
    - docker pull ${CI_IMAGE}:${CI_COMMIT_SHA} ||
      docker pull ${CI_IMAGE}:latest ||
      true
    - docker build
        --cache-from ${CI_IMAGE}:${CI_COMMIT_SHA}
        --cache-from ${CI_IMAGE}:latest
        -t ${CI_IMAGE}:${CI_COMMIT_SHA}
        -t ${CI_IMAGE}:latest
        .
    - docker push ${CI_IMAGE}:${CI_COMMIT_SHA}
    - docker push ${CI_IMAGE}:latest

test:
  stage: test
  image: ${CI_IMAGE}:${CI_COMMIT_SHA}
  services:
    - name: memsql/node:centos-6.8.13-47a99cbc09
      alias: memsql-master
    - name: memsql/node:centos-6.8.13-47a99cbc09
      alias: memsql-leaf
  variables:
    CI_IMAGE: psy3.memcompute.com/memsql-spark-utils/test-runner
    MEMSQL_HOST: memsql-master
    MEMSQL_PORT: "3306"
    MEMSQL_USER: root
    MEMSQL_DB: test
  script:
    - ./scripts/setup-services.sh
    - sbt test
    - sbt test -Dmysql.driver=mysql5
    - sbt test -Dmysql.driver=mysql8
